#!/bin/sh -e
# This script retrieves latest version from pip
# and all versions in docker hub for commitizen.
# If the version EXISTS then exit with error and stop pipeline

# requires pip
pip_latest_version() {
    python -m pip index versions commitizen | grep commitizen | grep -o -P '[0-9]+\.[0-9]+\.[0-9]+'
}

# requires curl & jq
list_cz_docker_versions() {
    curl -L -s 'https://registry.hub.docker.com/v2/repositories/commitizen/commitizen/tags/' | jq -r '.results[].name'
}

PIP_LATEST=$(pip_latest_version)
printf "latest pip version found:\n%s\n\n" "$PIP_LATEST"

tags=$(list_cz_docker_versions)
printf "Docker hub tags found:\n%s\n\n" "$tags"

if echo "${tags}" | grep -q "$PIP_LATEST"; then
    echo "Version already present, skipping other steps..."
else
    echo "Version not found... continue"
    echo 'Creating file: `VERSION`'
    echo "$PIP_LATEST" > VERSION
    echo "Setting variable 'version'"
    echo "::set-output name=version::$PIP_LATEST"
fi
