#!/bin/sh -e
# This script retrieves latest version from pip
# and all versions in docker hub for commitizen.
# If the version EXISTS then exit with error and stop pipeline

# requires pip
pip_latest_version() {
    python -m pip index versions commitizen | grep commitizen | grep -o -P '[0-9]+\.[0-9]+\.[0-9]+'
}

# requires wget, sed, gnu awk
list_cz_docker_versions() {
    image=commitizen/commitizen
    wget -q "https://registry.hub.docker.com/v1/repositories/${image}/tags" -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'
}

PIP_LATEST=$(pip_latest_version)
echo "latest pip version found '$PIP_LATEST'"

tags=$(list_cz_docker_versions)

if echo "${tags}" | grep -q "$PIP_LATEST"; then
    echo "Version already present, skipping other steps..."
else
    echo "Version not found... continue"
    echo 'Creating file: `VERSION`'
    echo "$PIP_LATEST" > VERSION
    echo "Setting variable 'version'"
    echo "::set-output name=version::$PIP_LATEST"
fi

